version: "3.5"
services:
  jovo-app:
    build:
      context: ./app
      dockerfile: app/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/app/src
    command: 'npm run start:dev'
    networks:
      - appnetwork
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
networks:
  appnetwork:
    driver: bridge